# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	Proj1_v2-Android-DebugGame  \
	Proj1_v2-Android-Development  \
	Proj1_v2-Android-Shipping  \
	Proj1_v2-Linux-DebugGame  \
	Proj1_v2-Linux-Development  \
	Proj1_v2-Linux-Shipping  \
	Proj1_v2-LinuxArm64-DebugGame  \
	Proj1_v2-LinuxArm64-Development  \
	Proj1_v2-LinuxArm64-Shipping  \
	Proj1_v2 \
	Proj1_v2Editor-Linux-DebugGame  \
	Proj1_v2Editor-Linux-Development  \
	Proj1_v2Editor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Proj1_v2Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Proj1_v2Editor-Linux-Debug


Proj1_v2-Android-DebugGame:
	 $(BUILD) Proj1_v2 Android DebugGame  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-Android-Development:
	 $(BUILD) Proj1_v2 Android Development  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-Android-Shipping:
	 $(BUILD) Proj1_v2 Android Shipping  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-Linux-DebugGame:
	 $(BUILD) Proj1_v2 Linux DebugGame  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-Linux-Development:
	 $(BUILD) Proj1_v2 Linux Development  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-Linux-Shipping:
	 $(BUILD) Proj1_v2 Linux Shipping  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-LinuxArm64-DebugGame:
	 $(BUILD) Proj1_v2 LinuxArm64 DebugGame  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-LinuxArm64-Development:
	 $(BUILD) Proj1_v2 LinuxArm64 Development  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2-LinuxArm64-Shipping:
	 $(BUILD) Proj1_v2 LinuxArm64 Shipping  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2: Proj1_v2-Linux-Development

Proj1_v2Editor-Linux-DebugGame:
	 $(BUILD) Proj1_v2Editor Linux DebugGame  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2Editor-Linux-Development:
	 $(BUILD) Proj1_v2Editor Linux Development  -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" $(ARGS)

Proj1_v2Editor: Proj1_v2Editor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/gg/Documents/MscDGD/PJR/Proj1_v2/Proj1_v2.uproject" -Game 

.PHONY: $(TARGETS)
